### ISSUE TITLE
Pull requests 不是特别方便，直接写在 issue 里了

### ISSUE THREAD

**Issue by zhaochunqi** [ryanhoo/Android-Proficiency-Exercise#3]
项目地址:[https://github.com/zhaochunqi/GankIO](https://github.com/zhaochunqi/GankIO)
下载地址: [http://fir.im/gankiopoc](http://fir.im/gankiopoc)

目前还存在的问题:

1. 离线数据库。
2. 轮播事件。

非常赞的 设计原型图，让我看到了自己的差距。 
因为今明两天没有时间再进行，所以提前提交了。之后有时间会继续完善。

Thanks.

**Comment by ryanhoo** [comment]
I already downloaded your app and I must say **nice work**!

**Comment by ryanhoo** [comment]
Also I suggest you add a label for this issue. You may pick either `for-fun` or `for-interview` from the right panel.

**Comment by zhaochunqi** [comment]
Thanks. Actually , I'm looking for a job...
